### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by VolDer77** [VolDer77/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by volder77-test** [comment]
<p>I’m looking for a trainee/junior Front-End developer position. I have no commercial experience but
                    I will try my best to keep up with my team. Have experience in making mobile responsive SPAs, CRUD
                    projects. Currently learning how to test my PET projects.</p>

**Comment by VolDer77** [comment]
LOL, ok
