### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by VolDer77** [VolDer77/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by volder77-test** [comment]
Some comment

**Comment by volder77-test** [comment]
<section>
                <h3>Languages</h3>
                <p class="language" lang="uk">
                  &#x1f1fa;&#x1f1e6; УКРАЇНСЬКА - NATIVE
                </p>
                <p class="language" lang="en">
                  &#x1f1fa;&#x1f1f8; ENGLISH - B2
                </p>
              </section>
              <section>
                <h3>Skills</h3>
                <p>HTML CSS FLEXBOX SASS/SCSS BEM</p>
                <p>JS ES5+ REACT REDUX TYPESCRIPT</p>
                <p>MATERIAL-UI BOOTSTRAP</p>
                <p>GIT REST-API FIREBASE</p>
                <p>FIGMA ADOBE-XD</p>
              </section>
              <section>
                <h3>Character</h3>
                <p>FIRST OF ALL: Genius, playboy, philanthropist.</p>
                <p class="tags small">AND LAST BUT NOT LEAST: EXPLORER STRAIGHTFORWARD
                  CONFIDENT CHALLENGING HILARIOUS
                </p>
              </section>
              <section>
                <h3>Likes&#x1f603;</h3>
                <p class="tags small">LEARNING NEW STUFF, TECHNOLOGY, TV SHOWS, COOL MOVIES, BASKETBALL</p>
              </section>
              <section>
                <h3>Education</h3>
                <ul class="timeline">
                  <li>
                    <div><em>2017 &ndash; present</em></div>
                    <div><strong>Lviv National University of Ivan Franko, Computer Science</strong></div>
                  </li>
                  <li>
                    <div><em>March 2020 &ndash; June 2020</em></div>
                    <div><strong>EPAM FrontEnd Online 2020</strong></div>
                  </li>
                </ul>
              </section>
